module.exports = [
  {
    token: "Haven",
    ticker: "XHV",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "$",
  },
  {
    token: "United States Dollar",
    ticker: "xUSD",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "$",
  },
  {
    token: "Bitcoin",
    ticker: "xBTC",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "$",
  },
  {
    token: "New Zealand Dollar",
    ticker: "xNZD",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "$",
  },
  {
    token: "Norwegian Krone",
    ticker: "xNOK",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "kr",
  },
  {
    token: "Japanese Yen",
    ticker: "xJPY",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "¥",
  },
  {
    token: "British Pound",
    ticker: "xGBP",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "£",
  },
  {
    token: "Euro",
    ticker: "xEUR",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "€",
  },
  {
    token: "Chinese Yuan",
    ticker: "xCNY",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "¥",
  },
  {
    token: "Swiss Franc",
    ticker: "xCHF",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "₣",
  },
  {
    token: "Canadian Dollar",
    ticker: "xCAD",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "$",
  },

  {
    token: "Australian Dollar",
    ticker: "xAUD",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "$",
  },
  {
    token: "Gold",
    ticker: "xGOLD",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "$",
  },
  {
    token: "Silver",
    ticker: "xSILV",
    price: "$1.00",
    change: "~ 0.00",
    symbol: "$",
  },
];
